## Project: End-to-End Customer Intelligence & Revenue Optimization System

## Phase 1 — Data Layer
#### Use real-world dataset (e-commerce, SaaS, telecom churn)
        Build a clean feature pipeline
        Handle missing data
        Build cohort features
        RFM analysis

In [94]:
import pandas as pd
import numpy as np
import streamlit as st
from fastapi import FastAPI
import uvicorn
import matplotlib.pyplot as plt
import seaborn as sns

In [95]:
orders = pd.read_csv('C:/Users/MIKEYkun/Downloads/OList Dataset/olist_orders_dataset.csv')
order_items = pd.read_csv('C:/Users/MIKEYkun/Downloads/OList Dataset/olist_order_items_dataset.csv')
payments = pd.read_csv('C:/Users/MIKEYkun/Downloads/OList Dataset/olist_order_payments_dataset.csv')
customers = pd.read_csv('C:/Users/MIKEYkun/Downloads/OList Dataset/olist_customers_dataset.csv')
products = pd.read_csv('C:/Users/MIKEYkun/Downloads/OList Dataset/olist_products_dataset.csv')
reviews = pd.read_csv('C:/Users/MIKEYkun/Downloads/OList Dataset/olist_order_reviews_dataset.csv')
sellers = pd.read_csv('C:/Users/MIKEYkun/Downloads/OList Dataset/olist_sellers_dataset.csv')
geo = pd.read_csv('C:/Users/MIKEYkun/Downloads/OList Dataset/olist_geolocation_dataset.csv')
category = pd.read_csv('C:/Users/MIKEYkun/Downloads/OList Dataset/product_category_name_translation.csv')

In [96]:
orders.info()
orders.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [97]:
orders['order_purchase_timestamp'] = pd.to_datetime(
    orders['order_purchase_timestamp']
)

In [98]:
df = orders.merge(customers, on='customer_id', how='left')
df = df.merge(order_items, on='order_id', how='left')
df = df.merge(payments, on='order_id', how='left')
df = df.merge(products, on='product_id', how='left')

In [99]:
df = df[df['order_status'] == 'delivered']
df['Revenue'] = df['price'] + df['freight_value']

In [100]:
df = df.merge(reviews[['order_id', 'review_score']],
              on='order_id',
              how='left')

In [101]:
df.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'customer_unique_id', 'customer_zip_code_prefix', 'customer_city',
       'customer_state', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value', 'payment_sequential',
       'payment_type', 'payment_installments', 'payment_value',
       'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm', 'Revenue',
       'review_score'],
      dtype='object')

In [102]:
df['product_category_name'] = df['product_category_name'].fillna("unknown")
df['review_score'] = df['review_score'].fillna(df['review_score'].median())

In [103]:
df = df.dropna(subset=['customer_unique_id'])

In [104]:
snapshot_date = df['order_purchase_timestamp'].max() + pd.Timedelta(days=1)

customer_df = df.groupby('customer_unique_id').agg({
    'order_purchase_timestamp': lambda x: (snapshot_date - x.max()).days,
    'order_id': 'nunique',
    'Revenue': 'sum',
    'review_score': 'mean'
}).reset_index()

In [105]:
customer_df.columns = [
    'CustomerID',
    'Recency',
    'Frequency',
    'Monetary',
    'AvgReviewScore'
]

In [106]:
df['OrderMonth'] = df['order_purchase_timestamp'].dt.to_period('M')
df['CohortMonth'] = df.groupby('customer_unique_id')['OrderMonth'].transform('min')

In [107]:
df['CohortIndex'] = (df['OrderMonth'] - df['CohortMonth']).apply(lambda x: x.n)

In [108]:
cohort_data = df.groupby(['CohortMonth', 'CohortIndex'])['customer_unique_id'] \
                .nunique() \
                .reset_index()

cohort_table = cohort_data.pivot(
    index='CohortMonth',
    columns='CohortIndex',
    values='customer_unique_id'
)

In [109]:
rfm = customer_df.copy()
rfm['R_score'] = pd.qcut(
    rfm['Recency'],
    5,
    labels=[5,4,3,2,1]
)

rfm['F_score'] = pd.qcut(
    rfm['Frequency'].rank(method='first'),
    5,
    labels=[1,2,3,4,5]
)

rfm['M_score'] = pd.qcut(
    rfm['Monetary'].rank(method='first'),
    5,
    labels=[1,2,3,4,5]
)

rfm['RFM_Score'] = (
    rfm['R_score'].astype(str) +
    rfm['F_score'].astype(str) +
    rfm['M_score'].astype(str)
)

In [110]:
rfm[['R_score','F_score','M_score']] = rfm[['R_score','F_score','M_score']].astype(int)

In [111]:
def segment_customer(row):
    
    if row['R_score'] >= 4 and row['F_score'] >= 4 and row['M_score'] >= 4:
        return "Champions 🔥"
    
    elif row['R_score'] >= 3 and row['F_score'] >= 3:
        return "Loyal Customers 💎"
    
    elif row['R_score'] >= 4 and row['F_score'] <= 2:
        return "New Customers 🆕"
    
    elif row['R_score'] <= 2 and row['F_score'] >= 3:
        return "At Risk ⚠️"
    
    elif row['R_score'] <= 2 and row['F_score'] <= 2:
        return "Lost Customers ❌"
    
    else:
        return "Potential Loyalist ⭐"

In [112]:
rfm['Segment'] = rfm.apply(segment_customer, axis=1)

In [113]:
rfm['Segment'].value_counts()

Segment
Loyal Customers 💎       27322
At Risk ⚠️              22230
Lost Customers ❌        14986
New Customers 🆕         14984
Potential Loyalist ⭐     7373
Champions 🔥              6463
Name: count, dtype: int64

## Phase 2 — Modeling
###  Churn Prediction (Classification)
        Logistic Regression
        Random Forest
        XGBoost
        Precision/Recall tuning (business tradeoffs)

###  LTV Prediction (Regression)
        Gradient boosting
        Evaluate with RMSE + business metrics

###  Recommendation System
        Collaborative filtering
        Matrix factorization OR
        Hybrid model

### PART 1 — Churn Prediction

In [114]:
cutoff_date = df['order_purchase_timestamp'].max() - pd.Timedelta(days=90)

In [115]:
train_df = df[df['order_purchase_timestamp'] <= cutoff_date]
future_df = df[df['order_purchase_timestamp'] > cutoff_date]

In [116]:
snapshot_date = train_df['order_purchase_timestamp'].max() + pd.Timedelta(days=1)

customer_features = train_df.groupby('customer_unique_id').agg({
    'order_purchase_timestamp': lambda x: (snapshot_date - x.max()).days,
    'order_id': 'nunique',
    'Revenue': 'sum',
    'review_score': 'mean',
    'freight_value': 'mean'
}).reset_index()

customer_features.columns = [
    'CustomerID',
    'Recency',
    'Frequency',
    'Monetary',
    'AvgReviewScore',
    'AvgFreight'
]

In [117]:
customer_features['AOV'] = (
    customer_features['Monetary'] /
    customer_features['Frequency']
)

In [118]:
customer_features['RepeatBuyer'] = np.where(
    customer_features['Frequency'] > 1, 1, 0
)

In [119]:
future_customers = future_df['customer_unique_id'].unique()

customer_features['Churn'] = np.where(
    customer_features['CustomerID'].isin(future_customers),
    0,  # active
    1   # churned
)

In [120]:
customer_features['Churn'].value_counts(normalize=True)

Churn
1    0.994411
0    0.005589
Name: proportion, dtype: float64

In [121]:
from sklearn.utils import resample
from sklearn.linear_model import LogisticRegression

In [122]:
X = customer_features[['Recency', 'Frequency', 'Monetary', 'AvgReviewScore', 'AOV', 'RepeatBuyer', 'AvgFreight']]
y = customer_features['Churn']

In [123]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [124]:
lr = LogisticRegression(max_iter=1000)
lr.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [125]:
y_pred = lr.predict(X_test)

In [126]:
from sklearn.metrics import classification_report, roc_auc_score

print(classification_report(y_test, y_pred))
print("ROC-AUC:", roc_auc_score(y_test, lr.predict_proba(X_test)[:,1]))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        84
           1       0.99      1.00      1.00     14980

    accuracy                           0.99     15064
   macro avg       0.50      0.50      0.50     15064
weighted avg       0.99      0.99      0.99     15064

ROC-AUC: 0.6095695053722423

C:\Users\MIKEYkun\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\MIKEYkun\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\MIKEYkun\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [127]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=300,
    max_depth=8,
    random_state=42
)
rf.fit(X_train, y_train)

RandomForestClassifier(max_depth=8, n_estimators=300, random_state=42)

In [128]:
from xgboost import XGBClassifier

In [129]:
xgb = XGBClassifier(
    n_estimators=500,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    eval_metric='logloss'
)

xgb.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=6, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=500, n_jobs=None,
              num_parallel_tree=None, ...)

In [130]:
from sklearn.metrics import roc_auc_score

roc_auc_score(y_test, xgb.predict_proba(X_test)[:,1])

0.5249221183800623

In [165]:
from sklearn.metrics import classification_report, roc_auc_score

# Logistic Regression
print("=== Logistic Regression ===")
print(classification_report(y_test, y_pred))
print("ROC-AUC:", roc_auc_score(y_test, lr.predict_proba(X_test)[:,1]))

=== Logistic Regression ===
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        84
           1       0.99      1.00      1.00     14980

    accuracy                           0.99     15064
   macro avg       0.50      0.50      0.50     15064
weighted avg       0.99      0.99      0.99     15064

ROC-AUC: 0.6095695053722423

C:\Users\MIKEYkun\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\MIKEYkun\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\MIKEYkun\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [166]:
# Random Forest
print("=== Random Forest ===")
print(classification_report(y_test, y_pred))
print("ROC-AUC:", roc_auc_score(y_test, rf.predict_proba(X_test)[:,1]))

=== Random Forest ===
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        84
           1       0.99      1.00      1.00     14980

    accuracy                           0.99     15064
   macro avg       0.50      0.50      0.50     15064
weighted avg       0.99      0.99      0.99     15064

C:\Users\MIKEYkun\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\MIKEYkun\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\MIKEYkun\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

ROC-AUC: 0.549544233581283

In [167]:
# XGBoost
print("=== XGBoost ===")
print(classification_report(y_test, y_pred))
print("ROC-AUC:", roc_auc_score(y_test, xgb.predict_proba(X_test)[:,1]))

=== XGBoost ===
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        84
           1       0.99      1.00      1.00     14980

    accuracy                           0.99     15064
   macro avg       0.50      0.50      0.50     15064
weighted avg       0.99      0.99      0.99     15064

ROC-AUC: 0.5249221183800623

C:\Users\MIKEYkun\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\MIKEYkun\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\MIKEYkun\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [168]:
y_prob = xgb.predict_proba(X_test)[:,1]

threshold = 0.35  # tuned
y_pred_custom = (y_prob > threshold).astype(int)

###  PART 2 — LTV PREDICTION (SERIOUS VERSION)

In [133]:
future_revenue = future_df.groupby('customer_unique_id')['Revenue'].sum().reset_index()
future_revenue.columns = ['CustomerID', 'FutureRevenue']

ltv_df = customer_features.merge(
    future_revenue,
    left_on='CustomerID',
    right_on='CustomerID',
    how='left'
).fillna(0)

In [134]:
X = ltv_df[['Recency', 'Frequency', 'Monetary', 'AvgReviewScore', 'AvgFreight', 'AOV', 'RepeatBuyer']]
y = ltv_df['FutureRevenue']

In [135]:
X_train_ltv, X_test_ltv, y_train_ltv, y_test_ltv = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [136]:
from sklearn.ensemble import GradientBoostingRegressor

gbr = GradientBoostingRegressor(
    n_estimators=500,
    max_depth=5,
    learning_rate=0.05
)

gbr.fit(X_train, y_train)

GradientBoostingRegressor(learning_rate=0.05, max_depth=5, n_estimators=500)

In [137]:
from sklearn.metrics import mean_squared_error, r2_score

rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

In [138]:
print("RMSE:", rmse)
print("R2 Score:", r2)

RMSE: 0.07467401273829244
R2 Score: -0.00560747663551453

###  PART 3 — RECOMMENDATION SYSTEM

In [139]:
from scipy.sparse import csr_matrix
from sklearn.decomposition import TruncatedSVD
from sklearn.metrics.pairwise import cosine_similarity

In [140]:
interaction = df.groupby(['customer_unique_id', 'product_id'])['order_id'].count().reset_index()
interaction.rename(columns={'order_id':'purchase_count'}, inplace=True)

In [141]:
customer_map = {id:i for i,id in enumerate(interaction['customer_unique_id'].unique())}
product_map = {id:i for i,id in enumerate(interaction['product_id'].unique())}
interaction['cust_idx'] = interaction['customer_unique_id'].map(customer_map)
interaction['prod_idx'] = interaction['product_id'].map(product_map)

In [142]:
sparse_matrix = csr_matrix((interaction['purchase_count'], 
                            (interaction['cust_idx'], interaction['prod_idx'])))

In [143]:
svd = TruncatedSVD(n_components=20, random_state=42)
latent_matrix = svd.fit_transform(sparse_matrix)

In [144]:
def get_top_similar_customers(cust_id, top_n=10):
    idx = customer_map[cust_id]
    cust_vec = latent_matrix[idx].reshape(1, -1)
    sim_scores = cosine_similarity(cust_vec, latent_matrix)[0]
    top_indices = np.argsort(sim_scores)[::-1][1:top_n+1]  # exclude self
    rev_map = {v:k for k,v in customer_map.items()}
    return [rev_map[i] for i in top_indices]

In [145]:
rfm['RFM_weight'] = rfm['R_score'].astype(int)*0.4 + rfm['F_score'].astype(int)*0.4 + rfm['M_score'].astype(int)*0.2
rfm_dict = rfm.set_index('CustomerID')['RFM_weight'].to_dict()

In [146]:
popularity = interaction.groupby('prod_idx')['purchase_count'].sum()
popularity = popularity / popularity.max()
popularity_dict = popularity.to_dict()

In [147]:
interaction['customer_unique_id'].head(5)

0    0000366f3b9a7992bf8c76cfdf3221e2
1    0000b849f77a49e4a4ce2b2a4ca5be3f
2    0000f46a3911fa3c0805444483337064
3    0000f6ccb0745a6a4b88665a16c9f078
4    0004aac84e0df4da2b147fca70cf8255
Name: customer_unique_id, dtype: object

In [148]:
def hybrid_recommend(cust_id, top_n=10):
    similar_customers = get_top_similar_customers(cust_id, top_n=50)
    similar_idx = [customer_map[c] for c in similar_customers]
    
    # Select purchases from similar customers
    mask = interaction['cust_idx'].isin(similar_idx)
    sub = interaction[mask]
    
    product_scores = {}
    for _, row in sub.iterrows():
        pid = row['prod_idx']
        cf_score = row['purchase_count'] / sub['purchase_count'].max()
        pop_score = popularity_dict.get(pid, 0)
        rfm_score = rfm_dict.get(cust_id, 0) / max(rfm_dict.values())
        final_score = 0.5*cf_score + 0.3*pop_score + 0.2*rfm_score
        product_scores[pid] = max(product_scores.get(pid, 0), final_score)
    
    top_products_idx = sorted(product_scores.items(), key=lambda x:x[1], reverse=True)[:top_n]
    rev_product_map = {v:k for k,v in product_map.items()}
    return [rev_product_map[i[0]] for i in top_products_idx]

# Example
hybrid_recommend('0000366f3b9a7992bf8c76cfdf3221e2', top_n=10)

['372645c7439f9661fbbacfd129aa92ec',
 '525947dbe3304ac32bf51602f9557c12',
 '42155695adbe665066ad812855fe523a',
 '68a058d125ba1544e726898f0b8c0523',
 '429e7401fafb76436f15e86498bd7364',
 'eab67bf937aaadc19f83383a331d2dd9',
 '120fa011365fc39efe382cba4e50999e',
 'cc1b0e67ffb98a08c886e8c3c27a915f',
 'eb53f94fdc60278efcef123bb275658a',
 'bd1aace4fad5609f005fd721b45dcec4']

### Phase 3 — Business Simulation Layer

In [149]:
import matplotlib.pyplot as plt
import seaborn as sns

In [150]:
rfm['RFM_weight'] = rfm['R_score'].astype(int)*0.4 + \
                    rfm['F_score'].astype(int)*0.4 + \
                    rfm['M_score'].astype(int)*0.2

In [151]:
churn_prob = lr.predict_proba(X_test)[:,1]  # probability of churn
churn_df = pd.DataFrame({
        'customer_unique_id': X_test.index, 'churn_prob': churn_prob
    })
churn_df['customer_unique_id'] = churn_df['customer_unique_id'].astype(str)
rfm['CustomerID'] = rfm['CustomerID'].astype(str)

In [152]:
sim_df = churn_df.merge(
    rfm[['CustomerID','RFM_weight']],
    left_on='customer_unique_id',
    right_on='CustomerID',
    how='left'
)
sim_df.drop(columns=['CustomerID'], inplace=True)
sim_df.head()

  customer_unique_id  churn_prob  RFM_weight
0               6601    0.996378         NaN
1              50641    0.992157         NaN
2               3465    0.995318         NaN
3              72535    0.996545         NaN
4               8115    0.994412         NaN

In [153]:
churn_threshold = 0.6  
high_risk = sim_df[sim_df['churn_prob'] > churn_threshold].copy()
print(f"Number of high-risk customers: {len(high_risk)}")
high_risk.head()

Number of high-risk customers: 15064

  customer_unique_id  churn_prob  RFM_weight
0               6601    0.996378         NaN
1              50641    0.992157         NaN
2               3465    0.995318         NaN
3              72535    0.996545         NaN
4               8115    0.994412         NaN

In [154]:
high_risk['churn_prob_after_offer'] = high_risk['churn_prob'] * (1 - retention_lift)

In [155]:
orders_items = orders.merge(order_items, on="order_id", how="left")

customer_revenue = orders_items.groupby("customer_id")["price"].sum().reset_index()
customer_revenue.rename(columns={"price": "total_revenue"}, inplace=True)

In [156]:
# Frequency: number of orders
customer_freq = orders.groupby("customer_id")["order_id"].nunique().reset_index()
customer_freq.rename(columns={"order_id": "order_count"}, inplace=True)

In [157]:
orders["order_purchase_timestamp"] = pd.to_datetime(orders["order_purchase_timestamp"])
last_order = orders.groupby("customer_id")["order_purchase_timestamp"].max().reset_index()
last_order["recency_days"] = (orders["order_purchase_timestamp"].max() - last_order["order_purchase_timestamp"]).dt.days

In [158]:
customer_features = customer_revenue.merge(customer_freq, on="customer_id")
customer_features = customer_features.merge(last_order[["customer_id","recency_days"]], on="customer_id")

customer_features["churn_prob"] = (
    0.4 * (customer_features["recency_days"] / customer_features["recency_days"].max()) +
    0.3 * (1 - customer_features["order_count"] / customer_features["order_count"].max()) +
    0.3 * (1 - customer_features["total_revenue"] / customer_features["total_revenue"].max())
)

customer_features["churn_prob"] = customer_features["churn_prob"].clip(0,1)

df_predictions = customer_features[["customer_id", "churn_prob"]]

print(df_predictions.head())

                        customer_id  churn_prob
0  00012a2ce6f8dcda20d059ce98491703    0.472607
1  000161a058600d5901f007fab4c27140    0.536080
2  0001fd6190edaaf884bcaf3d49edf079    0.604791
3  0002414f95344307404f0ace7a26f1d5    0.517898
4  000379cdec625522490c315e70c7a9fb    0.400515

In [159]:
df_model = df_predictions.copy()  # your churn predictions DataFrame
df_sim = customer_revenue.merge(df_model, on="customer_id", how="left")
df_sim["churn_prob"] = df_sim["churn_prob"].fillna(df_sim["churn_prob"].mean())

In [160]:
discount_amount = 10  # $10 retention offer
df_sim["discount_offered"] = discount_amount

In [161]:
discount_effectiveness = 0.3
df_sim["churn_prob_after_discount"] = df_sim["churn_prob"] * (1 - discount_effectiveness)
df_sim["retention_prob"] = 1 - df_sim["churn_prob_after_discount"]
df_sim["expected_revenue"] = df_sim["retention_prob"] * df_sim["total_revenue"]
df_sim["discount_cost"] = discount_amount  # cost per user
df_sim["net_profit"] = df_sim["expected_revenue"] - df_sim["discount_cost"]

In [162]:
total_expected_revenue = df_sim["expected_revenue"].sum()
total_discount_cost = df_sim["discount_cost"].sum()
roi = (total_expected_revenue - total_discount_cost) / total_discount_cost

print(f"High-Risk Customers: {len(high_risk)}")
print(f"Total Expected Revenue: ${total_expected_revenue:.2f}")
print(f"Total Discount Cost: ${total_discount_cost:.2f}")
print(f"Expected ROI: {roi*100:.2f}%")

High-Risk Customers: 15064
Total Expected Revenue: $9405827.26
Total Discount Cost: $994410.00
Expected ROI: 845.87%

In [163]:
simulations = 1000
roi_list = []

for i in range(simulations):
    simulated_retention = df_sim["churn_prob"] * (1 - np.random.normal(discount_effectiveness, 0.05, len(df_sim)))
    simulated_retention = 1 - simulated_retention
    expected_revenue_mc = simulated_retention * df_sim["total_revenue"]
    net_profit_mc = expected_revenue_mc - discount_amount
    roi_list.append(net_profit_mc.sum() / total_discount_cost)

print(f"Monte Carlo Average ROI: {np.mean(roi_list)*100:.2f}%")

Monte Carlo Average ROI: 845.86%

In [164]:
summary = pd.DataFrame({
    "Metric": ["Total Users", "Total Expected Revenue", "Total Discount Cost", "Expected ROI (%)"],
    "Value": [len(df_sim), total_expected_revenue, total_discount_cost, roi*100]
})

summary

                   Metric         Value
0             Total Users  9.944100e+04
1  Total Expected Revenue  9.405827e+06
2     Total Discount Cost  9.944100e+05
3        Expected ROI (%)  8.458701e+02

In [169]:
df_predictions.to_csv("df_predictions.csv", index=False)
high_risk.to_csv("df_simulation.csv", index=False)

In [170]:
import os

print("df_predictions exists:", os.path.exists("df_predictions.csv"))
print("df_simulation exists:", os.path.exists("df_simulation.csv"))

df_predictions exists: True
df_simulation exists: True

In [171]:
os.getcwd()

'C:\\Users\\MIKEYkun\\Downloads\\OList Dataset'